### ISSUE TITLE
`main` branch produced error when running  (`dev` seems to work)

### ISSUE THREAD

**Issue by MartinRJDagleish** [eljost/sympleints#2]
Hey, 

Just look through the repo and the `main` branch seemed to have an issue with a unknown function:
After recommened `git clone …` and install via `python -m pip install -e .`: `sympleints --help` produced 

```bash
    from sympleints.render_v2 import get_write_render
ModuleNotFoundError: No module named 'sympleints.render_v2'
```

Just wanted to let you know. I switched to `dev` branch now to check out the repo.

**Comment by eljost** [comment]
Should work now. But everything is highly in flux.
